# A login shell first reads /etc/profile and then ~/.bash_profile.
# A non-login shell reads from /etc/bash.bashrc and then ~/.bashrc.

# ssh foo@bar.com # login shell
# ssh foo@bar.com : # non-login shell
